### ISSUE TITLE
Stress-testing, performance, and miner optimizations for subnets

### ISSUE THREAD

**Issue by gregorycoppola** [hirosystems/stacks-subnets#130] opened 2022-07-11 14:49 UTC
**Is your feature request related to a problem? Please describe.**
There has been a variety of discussion on the `stacks-blockchain` side about the miner's performance during the Steady Lads mint.

Since this repo is a fork of `stacks-blockchain`, we could have analogous issues here.

We should start stress testing the hyper-chain.

If we find any fixes, we can backport them to `stacks-blockchain`, so that Hiro can contribute to `stacks-blockchain` organically through pursuing its business interest in hyper-chains.

**Describe the solution you'd like**
1) stress testing of hyper-chains
2) performance measurements
3) improvements

**Additional context**
This bug was found recently in the miner code https://github.com/stacks-network/stacks-blockchain/issues/3184

Maybe there are more things like this. In either way, we should presumably be fixing in both places.

**Comment by kantai** [comment] 2022-07-19 18:36
I think that the first area for pushing on performance in the hyperchain implementation is in _confirmation times_. One of the major performance benefits of hyperchains is that because they functionally have a single miner (whether they truly have a single miner, or a federated set), microblocks are guaranteed to be confirmed by the subsequent anchor block. This means that transactions can confirm much faster than in the `stacks-node`: hyperchain microblocks count as confirmed blocks in hyperchains.

The question is, in the current implementation, how well does microblock production work? If I broadcast a transaction to a hyperchain mempool, how quickly does it get included in a microblock? How much does this depend on stacks block confirmation times? Bitcoin confirmation times? How often does the hyperchain miner's block commit end up "missing" the intended stacks block?

**Comment by saralab** [comment] 2022-08-29 16:58
Profiling results so far here: https://www.notion.so/hiropbc/Profile-Results-1-10k-L2-Mints-712e8e92ac674f118662535eb4344d62

**Comment by gregorycoppola** [comment] 2022-09-09 17:22
Update: https://www.notion.so/In-Memory-Mempool-to-Eliminate-Time-Between-Processing-Transactions-663677018afc4ea2a62c9a7aa4667e22

**Comment by elenananana** [comment] 2022-09-27 18:25
nitpick- is it possible to change the name of this issue to swap out hyper-chain for subnet?

**Comment by obycode** [comment] 2023-02-17 02:03
Greg merged in the mempool optimizations and provided the testbeds. I think we should be good to close this issue. We can open new issues with more specific items later.

**Closed by obycode** 2023-02-17 02:03 UTC
